version: '3.11'
services:
    app:
        build: ./
        container_name: app
        env_file:
          - .env
        volumes:
            - mydata:/app/data
            - static:/app/staticfiles
        ports:
            - "8000:8000"
volumes:
    mydata:
    static:

